configfile: 'config/config.yml'

        
include: 'rules/common.smk'
include: 'rules/download.smk'


rule all_bids:
    input:
        json = 'bids/dataset_description.json'
    default_target: True

rule all_zips:
    input:
        zips_dir=expand('dicom_zips/site-{site}_subject-{subject}_ses-{session}_{suffix}.zip',zip,**get_zip_lists('resources/subjects.tsv'))

rule all_subjects_table:
    input:
        tsv='resources/subjects.tsv'


