configfile: 'config/config.yml'

include: 'rules/common.smk'

if config['init_lists'] == True:
    rule all_zip_lists:
        input:
            expand('resources/subjects_{suffix}.tsv',suffix=config['suffix_lut'].keys())


    include: 'rules/init_lists.smk'
else:
    rule all_bids:
        input:
            json = 'bids/dataset_description.json'
        default_target: True


    include: 'rules/download.smk'
    



