spred_url: 'https://spred.braincode.ca/spred/'
sites:
  - LHS

project_id: EPL09

tmp_download: '/localscratch'

remote_path_mri: '/data/projects/{project_id}_{site}/experiments/{project_id}_{site}_{subject}_01_SE01_MR'

tar2bids:
  LHS: 'resources/heuristics/cfmm_base.py'

containers:
  tar2bids: 'docker://khanlab/tar2bids:v0.0.6b'
