spred_url: 'https://spred.braincode.ca/spred/'
sites:
  - LHS
  - TWH
  - HSC 

init_lists: False #set this to True to grab new subject lists from XNAT

project_id: EPL31


session_lut:
  baseline: '01'
  followup: '02'


suffix_lut:
  T1w:
    include:
      - T1
      - SPGR
    exclude:
      - T1 flair 
  rest:
    include:
      - rest
      - Rest
      - RS_fMRI
    exclude:
      - PhysioLog
      - real
  dwimultishellAP:
    include:
      - diff_mb3_95dir_b2000_AP
    exclude:
      - FA
      - TENSOR
  dwimultishellPA:
    include:
      - diff_mb3_b0_PA
    exclude:
      - FA
      - TENSOR
  dwisingleshellAP:
    include:
      - DTI_64
    exclude:
      - FA
      - TENSOR
  dwisingleshellPA:
    include:
      - PA
      - P-A
    exclude:
      - diff_mb3
      - FA
      - TENSOR
      - ADC
      - TRACE
  dwiPepolar:
    include:
      - Pepolar
    exclude:
      - FA
      - TENSOR
      - ADC
      - TRACE       
