spred_url: 'https://spred.braincode.ca/spred/'
sites:
  #  - LHS
  - TWH
    #  - HSC 


project_id: EPL31


session_lut:
  baseline: '01'
  followup: '02'


suffix_lut:
  T1w:
    include:
      - T1
    exclude:
      - T1 flair 
  rest:
    include:
      - rest
      - Rest
      - RS_fMRI
    exclude:
      - PhysioLog
      - real
  dwiAP:
    include:
      - 95dir_b2000_AP
      - DTI_64
    exclude:
      - FA
      - TENSOR
  dwiPA:
    include:
      - PA
      - P-A
      - Pepolar
    exclude:
      - FA
      - TENSOR
      - ADC
      - TRACE
