spred_url: 'https://spred.braincode.ca/spred/'
sites:
  - LHS

project_id: EPL14

tmp_download: '/localscratch'

remote_path_mri: '/data/projects/{project_id}_{site}/experiments/{project_id}_{site_stripped}_{subject}_01_SE01_MR'

tar2bids: 
  LHS: 'resources/heuristics/lhs_b_eplink.py'

containers:
  tar2bids: 'docker://khanlab/tar2bids:v0.2.2'
